/*
*
*	INSERCIONES PRIMARIAS
*
*/

-- ROL

INSERT INTO ROL (NOMBRE, DESCRIPCION) 
VALUES ('Gerente General', 'Encargado de todas las agencias de una region');

INSERT INTO ROL (NOMBRE, DESCRIPCION) 
VALUES ('Gerente de agencia', 'Encargado de una agencia');

INSERT INTO ROL (NOMBRE, DESCRIPCION) 
VALUES ('Cajero', 'Realiza operaciones transaccionales del banco');

INSERT INTO ROL (NOMBRE, DESCRIPCION) 
VALUES ('Servicio al cliente', 'Realiza operaciones no transaccionales del banco');

-- AGENCIA
INSERT INTO AGENCIA (NOMBRE, DIRECCION, FONDOS) 
VALUES ('Agencia1', 'Direccion 1', 999999999.99);

-- TRABAJADOR

INSERT INTO TRABAJADOR (CUI, USUARIO, CONTRASENA, NOMBRES, APELLIDOS, TELEFONO, DIRECCION, IDROL, IDAGENCIA)
VALUES (1111111111111, 'usertrabajador1', 'passtrabajador1', 'Trabajador1', 'Trabajador1', 11111111,'Direccion trabajador1', 1, 1);

-- TIPOCUENTA

INSERT INTO TIPOCUENTA (NOMBRE, TASAINTERES)
VALUES ('Monetaria', 0);

INSERT INTO TIPOCUENTA (NOMBRE, TASAINTERES)
VALUES ('Ahorro', 0);

INSERT INTO TIPOCUENTA (NOMBRE, TASAINTERES)
VALUES ('Ahorro a plazo fijo', 0);

-- ESTADOCUENTA

INSERT INTO ESTADO (NOMBRE, DESCRIPCION)
VALUES ('Activada', 'Habilitada para cualquier proceso');

INSERT INTO ESTADO (NOMBRE, DESCRIPCION)
VALUES ('Desactivada', 'Deshabilitada para cualquier proceso');

INSERT INTO ESTADO (NOMBRE, DESCRIPCION)
VALUES ('Reactivada', 'Habilitada para cualquier proceso');


-- CUENTA

INSERT INTO CUENTA (IDCUENTA, FONDOS, INDIVIDUALIDAD, IDTIPOCUENTA, IDESTADO )
VALUES (12345678, 1000, 'V', 1, 1);
/*
INSERT INTO CUENTA (FONDOS, INDIVIDUALIDAD, IDTIPOCUENTA, IDESTADO, CUIPRESIDENTE, CUIVICEPRESIDENTE, CUICONTADOR)
VALUES (50000, F, 1, 1, FK, FK, FK);
*/

-- CLIENTE

INSERT INTO CLIENTE(CUI, USUARIO, CONTRASENA, NOMBRES, APELLIDOS, NACIMIENTO, PUNTOS)
VALUES (2650897270101, 'LuisGonzalez', 'luisgonzalez', 'Luis Felipe', 'Gonzalez Orellana', '1994-12-12', 0);

INSERT INTO CLIENTE 
VALUES (1234567890123, 'clienteprueba2', 'random', 'Juan', 'Perez', '2007-03-23', 0);

-- TIPOOPERACION

INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Crear cuenta', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Cambiar estado cuenta', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Solicitar chequera', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Cambiar estado chequera', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Solicitar prestamo', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Retiro', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Cambio de cheque', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Deposito', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Transferencia', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Pago de prestamo', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Pago normal Nomina', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Pago reintegro Nomina', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Pago liquidacion Nomina', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Pago bono Nomina', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Aceptar prestamo', 0);
INSERT INTO TIPOOPERACION (NOMBRE, PUNTOS)
VALUES ('Rechazar prestamo', 0);

-- OPERACION

-- 1. crear cuenta, 2. bloquear cuenta, 3. desbloquear cuenta, 
-- 4. solicitar chequera, 5. bloquear chequera, 6. desbloquear chequera;
-- solo cambian los permisos del usuario para 2 y 3 (los otros 4 solo puede hacerlos servicio al cliente);
INSERT INTO OPERACION (FECHA, IDCUENTA, IDTIPOOPERACION, CUITRABAJADOR)
VALUES ('2017-06-30 13-26-50',  12345678, 1 /* o 2, o 3, o 4, o 5, o 6*/, 1111111111111);

-- 7. solicitar prestamo
-- AGREGAR EL ATRIBUTO "CLIENTE" COMO FK EN LA TABLA OPERACION Y USARLO EN VEZ DE IDCUENTA EN ESTA CONSULTA
INSERT INTO OPERACION (FECHA, MONTO, CUICLIENTE, IDTIPOOPERACION, CUITRABAJADOR)
VALUES ('2017-06-30 13-26-50', 50000, 2650897270101, 7, 1111111111111);

-- 8. Retiro
INSERT INTO OPERACION (FECHA, MONTO, IDCUENTA, IDTIPOOPERACION, CUITRABAJADOR)
VALUES ('2017-06-30 13-26-50', 50000, 12345678, 8, 1111111111111);

-- 9. cambio de cheque, 10. deposito
INSERT INTO OPERACION (FECHA, MONTO, NOMBRETRANSACCIONISTA, IDCUENTA, IDTIPOOPERACION, CUITRABAJADOR)
VALUES ('2017-06-30 13-26-50', 50000, 'Juan Perez',12345678, 8, 1111111111111);

-- 11. transferencia
INSERT INTO OPERACION (FECHA, MONTO, CUENTATRANSFERENCIA, IDCUENTA, IDTIPOOPERACION, CUITRABAJADOR)
VALUES ('2017-06-30 13-26-50', 500, 1, 12345678, 11, 1111111111111);


-- MODALIDAD DE PAGO

INSERT INTO MODALIDADPAGO (NOMBRE, DESCRIPCION)
VALUES ('Quincenal', 'El cliente debe abonar a su deuda cada quince dias');

INSERT INTO MODALIDADPAGO (NOMBRE, DESCRIPCION)
VALUES ('Mensual', 'El cliente debe abonar a su deuda cada mes');

INSERT INTO MODALIDADPAGO (NOMBRE, DESCRIPCION)
VALUES ('Trimestral', 'El cliente debe abonar a su deuda cada tres meses');

-- TIPO DE PRESTAMO

INSERT INTO TIPOPRESTAMO (NOMBRE, TASAINTERES)
VALUES ('Tipo de prestamo 1', 0);

INSERT INTO TIPOPRESTAMO (NOMBRE, TASAINTERES)
VALUES ('Tipo de prestamo 2', 0);

INSERT INTO TIPOPRESTAMO (NOMBRE, TASAINTERES)
VALUES ('Tipo de prestamo 3', 0);

-- ESTADOPRESTAMO

INSERT INTO ESTADOPRESTAMO (NOMBRE, DESCRIPCION)
VALUES ('Pendiente de aprobacion', 'La solicitud de prestamo no ha sido respondida');

INSERT INTO ESTADOPRESTAMO (NOMBRE, DESCRIPCION)
VALUES ('Aprobado', 'El prestamo fue aprobado');

INSERT INTO ESTADOPRESTAMO (NOMBRE, DESCRIPCION)
VALUES ('Rechazado', 'El prestamo fue rechazado');

INSERT INTO ESTADOPRESTAMO (NOMBRE, DESCRIPCION)
VALUES ('Finalizado', 'La deuda por el prestamo ha sido saldada');


INSERT INTO CLIENTECUENTA
VALUES(2650897270101, 12345678, 0);
 
-- SELECTs *

SELECT * FROM AGENCIA;
SELECT * FROM ASOCIACIONCUENTA;
SELECT * FROM CANJE;
SELECT * FROM CHEQUE;
SELECT * FROM CLIENTE;
SELECT * FROM CLIENTECUENTA;
SELECT * FROM CUENTA;
SELECT * FROM ESTADO;
SELECT * FROM ESTADOPRESTAMO;
SELECT * FROM MODALIDADPAGO;
SELECT * FROM OPERACION;
SELECT * FROM PRESTAMO;
SELECT * FROM PRODUCTO;
SELECT * FROM PROVEEDOR;
SELECT * FROM ROL;
SELECT * FROM STOCK;
SELECT * FROM TIPOCUENTA;
SELECT * FROM TIPOOPERACION;
SELECT * FROM TIPOPRESTAMO;
SELECT * FROM TRABAJADOR;

TRUNCATE CLIENTECUENTA;
TRUNCATE CUENTA;

-- UPDATES

UPDATE ROL SET DESCRIPCION = 'Encargado de todas las agencias de una region.'
WHERE IDROL = 8;

UPDATE ROL SET DESCRIPCION = 'Encargado de una agencia.'
WHERE IDROL = 9;

UPDATE TIPOOPERACION SET NOMBRE = 'Deposito' WHERE IDTIPOOPERACION = 10;
SELECT * FROM TIPOOPERACION;

-- DELETES 
DELETE FROM AGENCIA;
DELETE FROM ASOCIACIONCUENTA;
DELETE FROM CANJE;
DELETE FROM CHEQUE;
DELETE FROM CLIENTE;
DELETE FROM CLIENTECUENTA;
DELETE FROM CUENTA;
DELETE FROM ESTADO;
DELETE FROM ESTADOPRESTAMO;
DELETE FROM MODALIDADPAGO;
DELETE FROM OPERACION;
DELETE FROM PRESTAMO;
DELETE FROM PRODUCTO;
DELETE FROM PROVEEDOR;
DELETE FROM ROL;
DELETE FROM STOCK;
DELETE FROM TIPOCUENTA;
DELETE FROM TIPOOPERACION;
DELETE FROM TIPOPRESTAMO;
DELETE FROM TRABAJADOR;